# Generated by Django 5.2.7 on 2025-10-21 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOFBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuvak_mandal_id', models.CharField(max_length=255)),
                ('member_name', models.CharField(max_length=255)),
                ('mobile_number', models.BigIntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=1000)),
                ('business', models.CharField(max_length=1000)),
                ('samaj_id', models.CharField(help_text='samaj or yuvak id', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.bloodgroup')),
                ('marital_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.maritalstatus')),
                ('relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.relationshiptype')),
                ('type_of_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.typeofbusiness')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.member')),
                ('fee_donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.typeofpayment')),
            ],
        ),
        migrations.CreateModel(
            name='UpdatedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField()),
                ('updated_data', models.JSONField()),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.member')),
            ],
        ),
    ]
